# Generated by Django 6.0.6 on 2026-06-26 11:51

import django.db.models.deletion
import submissions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institution', models.CharField(max_length=300)),
                ('position', models.CharField(choices=[('phd', 'PhD Student'), ('postdoc', 'Postdoc / Research Fellow'), ('assistant_prof', 'Assistant Professor'), ('associate_prof', 'Associate Professor'), ('full_prof', 'Full Professor'), ('researcher', 'Senior / Principal Researcher'), ('other', 'Other')], max_length=20)),
                ('research_field', models.CharField(help_text='e.g. Molecular Biology, Urban Planning, History of Art', max_length=200)),
                ('orcid', models.CharField(blank=True, max_length=30)),
                ('copyright_confirmed', models.BooleanField(default=False)),
                ('usage_rights_granted', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('file', models.ImageField(upload_to=submissions.models.image_upload_path)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What does this image show?')),
                ('method', models.CharField(help_text='How was this image created? (microscopy, illustration, photography, etc.)', max_length=300)),
                ('scientific_context', models.TextField(blank=True, help_text='Additional scientific background (optional)')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='submissions.submission')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
